### ISSUE TITLE
python 코드 파일 이름 규칙

### ISSUE THREAD

**Issue by antiline** [ridi/cms-sdk#30]
PEP8에 의하면 아래와 같이 되어 있습니다. 
```
https://www.python.org/dev/peps/pep-0008/#package-and-module-names
모듈은 소문자로 이루어진 짧은 이름을 사용해야 한다. 
모듈 이름의 가 독성을 높이기 위해 언더스코어를 사용할 수 있다. 
파이썬 패키지 또한 소문자로 이루어진 짧은 이름을 사용해야 한다. 
하지만 패키지의 경우에 는 언더스코어를 가급적 사용하지 않는다.
```

파일들을 보니 전부 camelcase로 되어 있습니다. 수정이 필요해 보입니다.

**Comment by Devgrapher** [comment]
thrift에서 자동 생성한 파일들때문에 그렇게되었는데요 그럼 thrift하위는 무시하고 나머지들은 PEP8을 따르도록 수정해보겠습니다.

**Comment by Devgrapher** [comment]
ridi-cms-sdk 2.1.0버전에 반영되어 릴리즈되었습니다. https://github.com/ridi/cms-sdk/commit/007d89880ced5cf1c0eb9338bb5aefabea232c07
